# Generated by Django 4.0.4 on 2022-06-01 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APFAST', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='studFirstName',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='staff',
            old_name='studLastName',
            new_name='staffFirstName',
        ),
        migrations.AddField(
            model_name='staff',
            name='email',
            field=models.EmailField(default='', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staff',
            name='staffLastName',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
